### PR TITLE
Added ComponentDidMount

### PR DESCRIPTION
**Pull request by MnaveedS**
The Latest release version 2.0.0 was not rendering any thing on the list after the inclusion of a flatlist.

Added `componentDidMount()` and `.toString()` to keyExtractor.

Tested and works for me

### CODE REVIEW

**Comment by alanshaw** [comment]
Please remove the fortmatting changes so I can review the fix

**Comment by MnaveedS** [comment]
The formatting are removed.

**Comment by emrekap** [comment]
`.toString()` to `keyExtractor` is very important. without it RN gives warning:

> Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.

**Comment by cschloer** [comment]
Bumping this PR - this package does not work without it

**Pull request merged**
